apiVersion: v2
name: vcluster-k0s
description: vcluster - Virtual Kubernetes Clusters (k0s)
home: https://vcluster.com
icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
keywords:
  - developer
  - development
  - sharing
  - share
  - multi-tenancy
  - tenancy
  - cluster
  - space
  - namespace
  - vcluster
  - vclusters
maintainers:
  - name: Spectro Cloud
    email: support@spectrocloud.com
sources:
  - https://github.com/spectrocloud/vcluster
type: application

version: 0.13.0-alpha.0-spectro-20230103