ARG KINE_VERSION="v0.14.14"
FROM rancher/kine:${KINE_VERSION} AS kine

# Build the manager binary
FROM us-central1-docker.pkg.dev/palette-images-dev/hardened-images/alpine:3.23-dev AS builder

WORKDIR /vcluster-dev

ARG TARGETOS
ARG TARGETARCH

ARG HELM_VERSION="v3.19.2"

RUN apk add --no-cache curl && mkdir -p /usr/local/bin

# Install helm binary
RUN curl -s https://get.helm.sh/helm-${HELM_VERSION}-linux-${TARGETARCH}.tar.gz > helm3.tar.gz && tar -zxvf helm3.tar.gz linux-${TARGETARCH}/helm && chmod +x linux-${TARGETARCH}/helm && mv linux-${TARGETARCH}/helm /usr/local/bin/helm && rm helm3.tar.gz && rm -R linux-${TARGETARCH}

# we use alpine for easier debugging
FROM us-central1-docker.pkg.dev/palette-images-dev/hardened-images/alpine:3.23-dev

# install runtime dependencies
RUN apk add --no-cache ca-certificates zstd tzdata

# Set root path as working directory
WORKDIR /

COPY vcluster .
COPY --from=kine /bin/kine /usr/local/bin/kine
COPY --from=builder /usr/local/bin/helm /usr/local/bin/helm

ENTRYPOINT ["/vcluster", "start"]
