name: Build and push head images

on:
  push:
    branches:
      - main

jobs:
  helm-unit-tests:
    name: Execute all helm tests
    if: github.repository_owner == 'loft-sh' # do not run on forks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Helm Unit Test Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --version v0.4.4
      - name: Run Helm Unit Tests
        run: |
          helm unittest chart

  go-unit-test:
    name: Execute all go tests
    if: github.repository_owner == 'loft-sh' # do not run on forks
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Execute unit tests
        run: ./hack/test.sh

  build-head-images:
    runs-on: ubuntu-latest
    needs: [helm-unit-tests, go-unit-test]
    name: Publish head images
    if: |
      github.repository_owner == 'loft-sh' &&
      github.ref_name == 'main'
    permissions:
      contents: read
      id-token: write # This is the key for OIDC cosign!
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          cache: false
          go-version-file: go.mod

      - name: Install just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Setup Cosgin
        uses: sigstore/cosign-installer@874852de93c66509b01dc7cd80f7a5385182d017 # main
        with:
          cosign-release: "v2.2.3"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GoReleaser and Build Images
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser.head_images.yaml --clean --skip=announce,archive,validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY_PRIVATE_KEY: ""
          CI_BRANCH: ${{ github.ref_name }}
